apiVersion: v1
kind: Pod
metadata:
  name: image-deployment
spec:
  template:
    metadata:
      labels:
        app: my-app 
    spec:
      containers:
      - name: my-appserver
        image: naresha553/my-app:2.0.0
        ports:
        - containerPort: 8080