apiVersion: apps/v1
kind: Pod
metadata:
  name: image-deployment
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app 
    spec:
      containers:
      - name: my-appserver
        image: naresha553/my-app:2.0.0
        ports:
        - containerPort: 8080