apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
    - name: busybox
      image: naresha553/my-app:2.0.0
      ports:
        - containerPort: 8080
          hostPort: 8080
