apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
    - name: my-app
      image: naresha553/my-app:2.0.0
      ports:
        - containerPort: 8080
          hostPort: 8080
